In [2]:
import numpy as np

#array start at int 1, end at int 20, incremented by 3
a = np.arange(1,20,3)

In [ ]:
#array of shape 3, random ints between 0 and 1
b = np.random.randint(0,2,3)

In [ ]:
#2d array
c1 = np.array([[10,20,45],[30,12,16],[42,17,56]])

#slice for first 2 rows. stop is exclusive in numpy.
c2 = c1[:2,:].copy()
#slice for last 2 rows
c3 = c1[-2:,:].copy()

In [ ]:
#create two 2d arrays
d1 = np.array([[1,2,3],[4,5,6]])
d2 = np.array([[6,5,4],[3,2,1]])

#stack horizontally
d3 = np.stack((d1,d2), axis=0)
#stack vertically
d4 = np.stack((d1,d2), axis=1)
#slice into smaller arrays
d5 = np.split(d3,2)

In [ ]:
#create two matrices
e1 = np.array([[5,7,2],[4,5,6],[7,4,2]])
e2 = np.array([[4,2],[6,2],[4,2]])

#it is possible when the 3x3 is multiplied onto the 2x3.
e3 = np.matmul(e1,e2)
print(e3)

#it is not possible when the 2x3 is multiplied onto the 3x3. matrix multiplication is not commutative.
try:
    e4 = np.matmul(e2,e1)
except ValueError as msg:
    print(msg)

In [ ]:
#create two arrays.
f1 = np.array([2,-1,-8])
f2 = np.array([3,1,-2])

#find the shape of X(f1).
print(np.shape(f1))
#find the number of dimensions of X(f1).
print(len(np.shape(f1)))

#reshape X(f1) to matrix of size (3,1) and determine number of dimensions after reshaping Y(f2) to a matrix of (3,1)
f3 = np.reshape(f1,[3,1])
f4 = np.reshape(f2,[3,1])
print(len(np.shape(f4)))
#??

(3,)
1
2


In [ ]:
# Broadcasting applies a 1D array to each row of a compatible 3x3 matrix.
g1 = np.array([[10,20,30],
                [40,50,60],
                [70,80,90]])
g2 = np.array([1,2,3])

# The vector is broadcast across all three rows.
g3 = g1 - g2
g4 = g1 * g2

print("Subtraction:")
print(g3)
print("Element-wise multiplication:")
print(g4)

Subtraction:
[[ 9 18 27]
 [39 48 57]
 [69 78 87]]
Element-wise multiplication:
[[ 10  40  90]
 [ 40 100 180]
 [ 70 160 270]]


In [ ]:
#solve the following two system of linear equations using matrices (find the values of x1 and x2) and determine the number of solutions using the functions.
# 2x1 +3x2 - 4x3 = 6, x1-4x2 = 8
#3y1-4y2+5y3=10, -y1+2y2-4y3=8
h1 = np.array([[2,3,-4],[1,-4,0]])
h2 = np.array([6,8])

h3 = np.linalg.lstsq(h1,h2)[0]

h4 = np.array([[3,-4,5],[-1,2,-4]])
h5 = np.array([10,8])

h6 = np.linalg.lstsq(h4,h5)[0]

print(h3)
print(h6)

[ 1.6692112 -1.5826972 -1.8524173]
[ 7.46067416 -4.62921348 -6.17977528]


In [ ]:
#publish the notebook as an HTML using github pages
#in the PR descriiption created above add the direct link to the HTML